--From the table PUBLISHER, AUTHOR and BOOK perform the following queries:  
--Part – A: 
--1. List all books with their authors.  
SELECT TITLE,AUTHORNAME
FROM BOOK B
LEFT JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID

--2. List all books with their publishers. 
SELECT TITLE,PUBLISHERNAME
FROM BOOK B
LEFT JOIN PUBLISHER P 
ON B.PUBLISHERID=P.PUBLISHERID

--3. List all books with their authors and publishers.
SELECT TITLE,AUTHORNAME,PUBLISHERNAME
FROM BOOK B
LEFT JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
LEFT JOIN PUBLISHER P 
ON B.PUBLISHERID=P.PUBLISHERID 

--4. List all books published after 2010 with their authors and publisher and price. 
SELECT TITLE,AUTHORNAME,PUBLISHERNAME,PRICE
FROM BOOK B
LEFT JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
LEFT JOIN PUBLISHER P 
ON B.PUBLISHERID=P.PUBLISHERID 
WHERE PUBLICATIONYEAR>2010

--5. List all authors and the number of books they have written.
SELECT AUTHORNAME,COUNT(BOOKID) AS TOTAL_BOOKS
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID
GROUP BY AUTHORNAME

--6. List all publishers and the total price of books they have published. 
SELECT PUBLISHERNAME,SUM(PRICE) AS TOTAL_PRICE
FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID=P.PUBLISHERID 
GROUP BY PUBLISHERNAME

--7. List authors who have not written any books. 
SELECT AUTHORNAME
FROM AUTHOR A
LEFT JOIN BOOK B
ON A.AUTHORID=B.AUTHORID
WHERE BOOKID IS NULL

--8. Display the total number of books written by each author along with the average price of their books. 
SELECT AUTHORNAME,COUNT(BOOKID) AS TOTAL_BOOKS,AVG(PRICE) AS AVG_PRICE
FROM AUTHOR A
LEFT JOIN BOOK B
ON A.AUTHORID=B.AUTHORID
GROUP BY AUTHORNAME

--9. lists each publisher along with the total number of books they have published, sorted from highest to 
--lowest. 
SELECT PUBLISHERNAME,COUNT(BOOKID) AS TOTAL_BOOKS
FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID
GROUP BY PUBLISHERNAME
ORDER BY COUNT(BOOKID) DESC

--10. Display number of books published each year. 
SELECT PUBLICATIONYEAR,COUNT(BOOKID) TOTAL_BOOKS
FROM BOOK
GROUP BY PUBLICATIONYEAR

--Part – B: 
--11. List the publishers whose total book prices exceed 500, ordered by the total price.
SELECT PUBLISHERNAME,SUM(PRICE) TOTAL_BOOK_PRICE
FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME
HAVING SUM(PRICE) >500
ORDER BY SUM(PRICE)

--12. List most expensive book for each author, sort it with the highest price.
SELECT AUTHORNAME,MAX(PRICE) MOST_EXPENSIVE
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID=B.AUTHORID
GROUP BY AUTHORNAME
ORDER BY MAX(PRICE) DESC

--13. Display publisher name and difference between maximum and minimum book price.
SELECT PUBLISHERNAME,MAX(PRICE) - MIN(PRICE) DIFFERNCE
FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME

--14. List publisher name and total price of books published each year.
SELECT PUBLISHERNAME,SUM(PRICE) TOTAL_PRICE,PUBLICATIONYEAR
FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME,PUBLICATIONYEAR

--15. Display author name and total price of books sorted by highest total price.
SELECT AUTHORNAME,SUM(PRICE) TOTAL_PRICE
FROM AUTHOR A
JOIN BOOK B
ON A.AUTHORID=B.AUTHORID
GROUP BY AUTHORNAME
ORDER BY SUM(PRICE) DESC

--From the above table EMPLOYEE_MASTER perform the following queries:  
--Part – C: 

CREATE TABLE EMPLOYEE_MASTER
(	
	EMPLOYEENO VARCHAR(10),
	NAME VARCHAR(30),
	MANAGERNO VARCHAR(10)
)

INSERT INTO EMPLOYEE_MASTER
VALUES
('E01','TARUN',NULL),
('E02','ROHAN','E02'),
('E03','PRIYA','E01'),
('E04','MILAN','E03'),
('E05','JAY','E01'),
('E06','ANJANA','E04')

--16. Retrieve the names of employee along with their manager’s name from the Employee table.
SELECT E1.NAME,E2.NAME
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2
ON E1.MANAGERNO=E2.EMPLOYEENO

--17. Display employees who are managers.
SELECT E2.NAME
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2
ON E1.MANAGERNO=E2.EMPLOYEENO

--18. Display number of employees working under each manager.
SELECT E1.NAME,COUNT(E2.EMPLOYEENO) AS TOTAL_EMP
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2
ON E1.EMPLOYEENO=E2.MANAGERNO
GROUP BY E1.NAME

--19. Display the employee’s name along with their manager’s name and senior manager name.
SELECT E1.NAME EMPLOYEE,E2.NAME MANAGER,E3.NAME SENOIR_MANAGER
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2
ON E1.MANAGERNO=E2.EMPLOYEENO
JOIN EMPLOYEE_MASTER E3
ON E2.MANAGERNO=E3.EMPLOYEENO

--20. Display managers and count of employees under them in descending order. 
SELECT E1.NAME,COUNT(E2.EMPLOYEENO) AS TOTAL_EMP
FROM EMPLOYEE_MASTER E1
JOIN EMPLOYEE_MASTER E2
ON E1.EMPLOYEENO=E2.MANAGERNO
GROUP BY E1.NAME
ORDER BY TOTAL_EMP DESC