--From the table STUDENT perform the following queries:  
--Part – A: 
--1. Display all students whose SPI is greater than 8. 
WITH ALL_STU AS
(
SELECT *
FROM STUDENT
)
SELECT *
FROM ALL_STU
WHERE SPI>8

--2. Display average SPI of all students. 
WITH ALL_STU AS
(
SELECT AVG(SPI) AVG_SPI
FROM STUDENT
)
SELECT AVG_SPI
FROM ALL_STU

--3. Display total number of students in each branch.
WITH ALL_STU AS
(
SELECT BRANCH,COUNT(STDID) TOTAL_STU
FROM STUDENT
GROUP BY BRANCH
)
SELECT BRANCH,TOTAL_STU
FROM ALL_STU

--4. Display students who belong to RAJKOT city.
WITH ALL_STU AS
(
SELECT *
FROM STUDENT
)
SELECT *
FROM ALL_STU
WHERE CITY='RAJKOT'

--5. Find branch names that appear more than once.
WITH ALL_STU AS
(
SELECT BRANCH,COUNT(STDID) TOTAL_APP
FROM STUDENT
GROUP BY BRANCH
)
SELECT *
FROM ALL_STU
WHERE TOTAL_APP>1

--6. Display row number for each student. 
WITH ALL_STU AS
(
SELECT STDID,SNAME,BRANCH,SPI,ROW_NUMBER() OVER(ORDER BY SPI DESC) RN
FROM STUDENT
)
SELECT *
FROM ALL_STU

--7. Display top 3 students based on SPI. 
WITH ALL_STU AS
(
SELECT STDID,SNAME,BRANCH,SPI,DENSE_RANK() OVER(ORDER BY SPI DESC) DR
FROM STUDENT
)
SELECT *
FROM ALL_STU
WHERE DR<=3

--8. Display students having maximum SPI. 
WITH STU AS
(
SELECT SNAME,BRANCH,SPI,DENSE_RANK() OVER(ORDER BY SPI DESC) DR
FROM STUDENT
)
SELECT SNAME,BRANCH,SPI
FROM STU
WHERE DR=1

--9. Display students having minimum SPI.
WITH STU AS
(
SELECT SNAME,BRANCH,SPI,DENSE_RANK() OVER(ORDER BY SPI) DR
FROM STUDENT
)
SELECT SNAME,BRANCH,SPI
FROM STU
WHERE DR=1

--10. Display branch -wise rank of students.
WITH STU AS
(
SELECT SNAME,BRANCH,SPI,DENSE_RANK() OVER(PARTITION BY BRANCH ORDER BY SPI DESC) DR
FROM STUDENT
)
SELECT SNAME,BRANCH,SPI,DR AS RANK
FROM STU 

 
--Part – B: 
--11. Display students SPI average belonging to Computer branch.
WITH STU AS
(
SELECT BRANCH,AVG(SPI) AVG_SPI
FROM STUDENT
GROUP BY BRANCH
)
SELECT *
FROM STU
WHERE BRANCH='COMPUTER'

--12. Display students whose SPI is greater than average SPI of his/her branch.
WITH STU AS
(
SELECT SNAME,BRANCH,SPI,AVG(SPI) OVER(PARTITION BY BRANCH) BR_AVG
FROM STUDENT
)
SELECT SNAME,BRANCH,SPI,BR_AVG
FROM STU
WHERE SPI>BR_AVG

--13. Display branch having more than 2 students. 
WITH STU AS 
(
SELECT BRANCH,COUNT(STDID) CT
FROM STUDENT
GROUP BY BRANCH
)
SELECT BRANCH
FROM STU
WHERE CT>2

--14. Display branches having average SPI between 7 and 9 
WITH BRANCHES AS
(
SELECT BRANCH,AVG(SPI) AVG_SPI
FROM STUDENT
GROUP BY BRANCH
)
SELECT BRANCH,AVG_SPI
FROM BRANCHES
WHERE AVG_SPI BETWEEN 7 AND 9

--15. Display students whose SPI is lower than overall average SPI. 
WITH STU AS
(
SELECT SNAME,BRANCH,SPI,AVG(SPI) OVER() AVG_SPI
FROM STUDENT
)
SELECT SNAME,BRANCH,SPI
FROM STU
WHERE SPI < AVG_SPI

--Part – C: 
--16. Display branches having exactly one student. 
WITH STU AS
(
SELECT BRANCH,COUNT(STDID) TOTAL_STU
FROM STUDENT
GROUP BY BRANCH
)
SELECT BRANCH
FROM STU
WHERE TOTAL_STU=1

--17. Display branch having highest average SPI. 
WITH BRANCHES AS
(
SELECT BRANCH,AVG(SPI) AVG_SPI
FROM STUDENT
GROUP BY BRANCH
),
RANKING AS
(
SELECT BRANCH,DENSE_RANK() OVER(ORDER BY AVG_SPI DESC) DR
FROM BRANCHES
)
SELECT B.BRANCH,AVG_SPI
FROM BRANCHES B
INNER JOIN RANKING R
ON B.BRANCH=R.BRANCH
WHERE DR=1

--18. Display branch having lowest average SPI.
WITH BRANCHES AS
(
SELECT BRANCH,AVG(SPI) AVG_SPI
FROM STUDENT
GROUP BY BRANCH
),
RANKING AS
(
SELECT BRANCH,DENSE_RANK() OVER(ORDER BY AVG_SPI) DR
FROM BRANCHES
WHERE BRANCH IS NOT NULL
)
SELECT B.BRANCH,AVG_SPI
FROM BRANCHES B
INNER JOIN RANKING R
ON B.BRANCH=R.BRANCH
WHERE DR=1

--19. Display students whose SPI is lower than branch average SPI.
WITH STU AS
(
SELECT SNAME,BRANCH,SPI,AVG(SPI) OVER(PARTITION BY BRANCH) AVG_SPI
FROM STUDENT
)
SELECT SNAME,BRANCH,SPI
FROM STU
WHERE SPI<AVG_SPI

--20. Display branches having maximum number of students.
WITH BRANCHES AS
(
SELECT BRANCH,COUNT(STDID) TOTAL_STU
FROM STUDENT
GROUP BY BRANCH
),
RANKING AS
(
SELECT BRANCH,DENSE_RANK() OVER(ORDER BY TOTAL_STU DESC) DR
FROM BRANCHES
)
SELECT B.BRANCH,TOTAL_STU
FROM BRANCHES B
JOIN RANKING R
ON R.BRANCH = B.BRANCH
WHERE DR=1