--Implement AFTER Triggers for Automatic Execution After Data Operations 
--EMPLOYEE_LOG (LOGID, EID, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE) 
--From the table EMPLOYEE perform the following queries:  
--Part – A: 
--1. Create trigger for printing message after employee record insertion. 
CREATE TRIGGER TR_INS_MSG
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
DECLARE @NAME VARCHAR(30)
SELECT @NAME=FIRSTNAME
FROM inserted
PRINT @NAME+' INSERTED'
END

--2. Create trigger for printing message after employee record update.
CREATE OR ALTER TRIGGER TR_UPDATE_MSG
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
PRINT 'RECORD UPDATED'
END

--3. Create trigger for printing message after employee record deletion.
CREATE TRIGGER TR_DEL_MSG
ON EMPLOYEE
AFTER DELETE
AS
BEGIN
DECLARE @NAME VARCHAR(30)
SELECT @NAME=FIRSTNAME
FROM deleted
PRINT @NAME+' DELETED'
END

--4. Create trigger for printing message after employee salary increment.
CREATE OR ALTER TRIGGER TR_SAL_INCRE
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
DECLARE @SAL1 VARCHAR(30),@SAL2 VARCHAR(30)
SELECT @SAL2=SALARY
FROM inserted
SELECT @SAL1=SALARY
FROM deleted
IF @SAL2 > @SAL1
BEGIN
PRINT 'SALARY INCREASED FROM '+@SAL1+' TO '+@SAL2
END
END

--5. Create trigger for automatically converting CITY names into uppercase during insertion. 
CREATE OR ALTER TRIGGER TR_CITY_UPPER
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
DECLARE @CITY VARCHAR(30)
SELECT @CITY=CITY
FROM inserted
UPDATE EMPLOYEE
SET CITY=UPPER(@CITY)
WHERE CITY=@CITY
END

--Part – B: 
--6. Create trigger for updating employee city and printing old city and new city name.
CREATE OR ALTER TRIGGER TR_UPDT_CITY
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
DECLARE @CITY1 VARCHAR(30),@CITY2 VARCHAR(30)
SELECT @CITY1=CITY
FROM inserted
SELECT @CITY2=CITY
FROM deleted
PRINT @CITY2+' UPDATED TO '+@CITY1
END

--7. Create trigger for automatically setting CITY as 'RAJKOT' if no city value is entered during employee 
--insertion.
CREATE OR ALTER TRIGGER TR_DFLT_CITY
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
DECLARE @CITY VARCHAR(30)
SELECT @CITY=CITY
FROM inserted
IF @CITY IS NULL
BEGIN
UPDATE EMPLOYEE
SET CITY='RAJKOT'
WHERE CITY=@CITY
END
END

--8. Create trigger for automatically adding current year in JOININGYEAR if no value is entered.
CREATE OR ALTER TRIGGER TR_DFLT_YEAR
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
DECLARE @YEAR VARCHAR(30)
SELECT @YEAR=JOININGYEAAR
FROM inserted
IF @YEAR IS NULL
BEGIN
UPDATE EMPLOYEE
SET JOININGYEAAR=DATEPART(YYYY,GETDATE())
WHERE JOININGYEAAR=@YEAR
END
END

--9. Create trigger for printing employee full name after new employee insertion.
CREATE TRIGGER TR_INS_FNAME
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
DECLARE @NAME VARCHAR(30)
SELECT @NAME=FIRSTNAME
FROM inserted
PRINT @NAME+' INSERTED'
END

--10. Create trigger for automatically assigning department as ‘GENERAL’ if DEPARTMENT value is NULL. 
CREATE OR ALTER TRIGGER TR_DFLT_DEPT
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
DECLARE @DEPT VARCHAR(50)
SELECT @DEPT=DEPARTMENT
FROM inserted
IF @DEPT IS NULL
BEGIN
UPDATE EMPLOYEE
SET DEPARTMENT='GENERAL'
WHERE DEPARTMENT=@DEPT
END
END

--Part – C: 
--11. Create trigger for storing updated employee details such as EID, old salary, new salary, old department, 
--new department, and update date into EMPLOYEE_UPDATE_LOG table.
CREATE TABLE EMPLOYEE_UPDATE_LOG
(EID INT,OLD_SALARY DECIMAL(10,2),NEW_SALARY DECIMAL(10,2),
OLD_DEPT VARCHAR(30),NEW_DEPT VARCHAR(30),UPDATE_DATE DATETIME)

CREATE OR ALTER TRIGGER TR_EMP_UPDT_LOG
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
DECLARE @EID INT,@OSAL VARCHAR(30),@NSAL VARCHAR(30),@ODEPT VARCHAR(30),@NDEPT VARCHAR(30)
SELECT @EID=EID,@OSAL=SALARY,@ODEPT=DEPARTMENT
FROM deleted
SELECT @NSAL=SALARY,@NDEPT=DEPARTMENT
FROM inserted
INSERT INTO EMPLOYEE_UPDATE_LOG
VALUES(@EID,@OSAL,@NSAL,@ODEPT,@NDEPT,GETDATE())
END

--12. Create trigger for storing newly inserted employee details with insertion date into 
--EMPLOYEE_INSERT_LOG table.
CREATE TABLE EMPLOYEE_INSERT_LOG
(EID INT,FIRSTNAME VARCHAR(30),LASTNAME VARCHAR(30),DEPARTMENT VARCHAR(30),SALARY DECIMAL(10,2),
CITY VARCHAR(30),GENDER VARCHAR(30),JOININGYEAR INT)

CREATE OR ALTER TRIGGER TR_EMP_INSRT_LOG
ON EMPLOYEE
AFTER INSERT
AS
BEGIN
INSERT INTO EMPLOYEE_INSERT_LOG
SELECT * FROM inserted
END

--13. Create trigger for storing old and new FIRSTNAME values after employee name update into 
--NAME_CHANGE_LOG table. 
CREATE TABLE NAME_CHANGE_LOG
(OLD_NAME VARCHAR(30),NEW_NAME VARCHAR(30))

CREATE OR ALTER TRIGGER TR_NM_UPDT
ON EMPLOYEE
AFTER UPDATE
AS
BEGIN
DECLARE @ONAME VARCHAR(30),@NNAME VARCHAR(30)
SELECT @ONAME=FIRSTNAME FROM deleted
SELECT @NNAME=FIRSTNAME FROM inserted
IF @ONAME!=@NNAME
BEGIN
INSERT INTO NAME_CHANGE_LOG
VALUES(@ONAME,@NNAME)
END
END

--14. Create trigger for storing old city and new city details into CITY_UPDATE_LOG table after city update. 
--15. Implement INSTEAD OF INSERT trigger on EMPLOYEE table to automatically remove extra spaces from 
--FIRSTNAME and LASTNAME before insertion.