--Implement Window Functions for Advanced Data Analysis
--From the table STUDENT perform the following queries:  
--Part � A: 
--1. Display rank of students based on SPI. 
SELECT SNAME, BRANCH, SPI, RANK() OVER(ORDER BY SPI DESC) RANK
FROM STUDENT

--2. Display dense rank of students based on SPI. 
SELECT SNAME, BRANCH, SPI, DENSE_RANK() OVER(ORDER BY SPI DESC) DENSE_RANK
FROM STUDENT

--3. Display sequential number for each student record.
SELECT SNAME, BRANCH, SPI, ROW_NUMBER() OVER(ORDER BY SPI DESC) ROW_NUMBER
FROM STUDENT

--4. Display branch-wise rank of students.
SELECT SNAME, BRANCH, SPI, RANK() OVER(PARTITION BY BRANCH ORDER BY SPI DESC) RANK
FROM STUDENT

--5. Display branch-wise dense ranking of students.
SELECT SNAME, BRANCH, SPI, DENSE_RANK() OVER(PARTITION BY BRANCH ORDER BY SPI DESC) DENSE_RANK
FROM STUDENT

--6. Display branch-wise sequential numbering of students.
SELECT SNAME, BRANCH, SPI, ROW_NUMBER() OVER(PARTITION BY BRANCH ORDER BY SPI DESC) ROW_NUMBER
FROM STUDENT

--7. Display SNAME, Current SPI, Previous SPI and SPI Difference with previous student in ascending order of 
--SPI. 
SELECT SNAME, SPI, LAG(SPI) OVER(ORDER BY SPI) PRE_SPI, SPI-LAG(SPI) OVER(ORDER BY SPI) DIFF_SPI
FROM STUDENT
ORDER BY SPI

--8. Display SNAME, Current SPI, Next SPI and SPI Difference with next student in descending order of SPI.
SELECT SNAME, SPI, LEAD(SPI) OVER(ORDER BY SPI) NEXT_SPI, LEAD(SPI) OVER(ORDER BY SPI) - SPI DIFF_SPI
FROM STUDENT
ORDER BY SPI DESC

--9. Display top 3 students based on SPI. 
SELECT *
FROM (SELECT SNAME, BRANCH, SPI, DENSE_RANK() OVER(ORDER BY SPI DESC) RK
    FROM STUDENT) AS RANK_TB
WHERE RK<=3

--10. Display top 2 students from each branch. 
SELECT *
FROM (SELECT SNAME, BRANCH, SPI, DENSE_RANK() OVER(PARTITION BY BRANCH ORDER BY SPI DESC) RK
    FROM STUDENT) AS RANK_TB
WHERE RK<=2

--Part � B: 
--11. Display 5th highest SPI.
SELECT *
FROM (SELECT SNAME, BRANCH, SPI, DENSE_RANK() OVER(ORDER BY SPI DESC) RK
    FROM STUDENT) AS RANK_TB
WHERE RK=5

--12. Display 6th highest SPI. 
SELECT *
FROM (SELECT SNAME, BRANCH, SPI, DENSE_RANK() OVER(ORDER BY SPI DESC) RK
    FROM STUDENT) AS RANK_TB
WHERE RK=6

--13. Display students having same ranking.
SELECT *
FROM (SELECT SNAME, BRANCH, SPI, DRK, LEAD(DRK) OVER(ORDER BY SPI DESC) NDRK, LAG(DRK) OVER(ORDER BY SPI DESC) PDRK
    FROM (SELECT SNAME, BRANCH, SPI, DENSE_RANK() OVER(ORDER BY SPI DESC) DRK
        FROM STUDENT) AS RANK_TB) AS OUTER_TB
WHERE DRK=NDRK OR DRK=PDRK

--14. Display SNAME, Previous SPI, Current SPI and Next SPI based on ascending order of SPI.
SELECT SNAME, LAG(SPI) OVER(ORDER BY SPI) PREV_SPI, SPI, LEAD(SPI) OVER(ORDER BY SPI) NEXT_SPI
FROM STUDENT

--15. Display topper of each branch. 
SELECT *
FROM (SELECT SNAME, BRANCH, SPI, RANK() OVER(PARTITION BY BRANCH ORDER BY SPI DESC) RK
    FROM STUDENT) AS TOPER_TB
WHERE RK=1


--Part � C: 
--16. Display students whose SPI is greater than the previous student and less than the next student.
SELECT *
FROM (SELECT SNAME, BRANCH, SPI, LAG(SPI) OVER(ORDER BY SPI) PREV, LEAD(SPI) OVER(ORDER BY SPI) NEXT
    FROM STUDENT) AS RANK_TB
WHERE SPI>PREV AND SPI<NEXT

--17. Display branch-wise second topper students.
SELECT *
FROM (SELECT SNAME, BRANCH, SPI, DENSE_RANK() OVER(PARTITION BY BRANCH ORDER BY SPI DESC) RK
    FROM STUDENT) AS RANK_TB
WHERE RK=2

--18. Display students whose rank and dense rank are different.
SELECT *
FROM (SELECT SNAME, BRANCH, SPI, DENSE_RANK() OVER(ORDER BY SPI DESC) DRK, RANK() OVER(ORDER BY SPI DESC) RK
    FROM STUDENT) AS RANK_TB
WHERE DRK!=RK

--19. Display consecutive students having same branch ordered by SPI. 
SELECT *
FROM (SELECT SNAME, BRANCH, SPI, LAG(BRANCH) OVER(ORDER BY SPI) PREV, LEAD(BRANCH) OVER(ORDER BY SPI) NEXT
    FROM STUDENT) AS RANK_TB
WHERE BRANCH=PREV OR BRANCH=NEXT

--20. Display students whose SPI difference with previous student is maximum.
SELECT TOP 1
    *
FROM (
    SELECT SNAME, BRANCH, SPI, SPI - LAG(SPI) OVER(ORDER BY SPI) AS DIFF
    FROM STUDENT
) AS RANK_TB
ORDER BY DIFF DESC;