--EMPLOYEE_LOG (LOGID, EID, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE) 
--From the table EMPLOYEE perform the following queries:  
--Part – A: 
--1. Create trigger for preventing removal of employees from the table.
CREATE OR ALTER TRIGGER TR_PREVENT_DEL
ON EMPLOYEE
INSTEAD OF DELETE
AS
BEGIN
PRINT 'Cannot delete data'
END

--2. Create INSTEAD OF DELETE trigger to prevent deletion of employee records and store deleted data into 
--EMPLOYEE_LOG table. 
CREATE TABLE EMPLOYEE_LOG (LOGID INT IDENTITY(1,1) PRIMARY KEY, EID INT, OLDVALUE VARCHAR(30),
NEWVALUE VARCHAR(30), FIELDNAME VARCHAR(30), OPERATIONTYPE VARCHAR(30), LOGDATE DATETIME)

CREATE TRIGGER TR_DEL_EMP
ON EMPLOYEE
INSTEAD OF DELETE
AS
BEGIN
DECLARE @EID INT,@NAME VARCHAR(30)
SELECT @EID=EID, @NAME=FIRSTNAME 
FROM deleted
INSERT INTO EMPLOYEE_LOG(EID,OLDVALUE,FIELDNAME,OPERATIONTYPE,LOGDATE)
VALUES(@EID,@NAME,'FIRSTNAME','DELETE',GETDATE())
END

--3. Create INSTEAD OF trigger to log all operations on EMPLOYEE table (INSERT/UPDATE/DELETE) into 
--EMPLOYEE_LOG table. 
CREATE OR ALTER TRIGGER TR_INS_EMP
ON EMPLOYEE
INSTEAD OF INSERT
AS
BEGIN
DECLARE @EID INT,@NAME VARCHAR(30)
SELECT @EID=EID, @NAME=FIRSTNAME 
FROM inserted
INSERT INTO EMPLOYEE_LOG(EID,NEWVALUE,FIELDNAME,OPERATIONTYPE,LOGDATE)
VALUES(@EID,@NAME,'FIRSTNAME','INSERT',GETDATE())
END

CREATE OR ALTER TRIGGER TR_UPD_EMP
ON EMPLOYEE
INSTEAD OF UPDATE
AS
BEGIN
DECLARE @EID INT,@ONAME VARCHAR(30),@NNAME VARCHAR(30)
SELECT @EID=EID, @NNAME=FIRSTNAME 
FROM inserted
SELECT @EID=EID, @ONAME=FIRSTNAME 
FROM deleted
INSERT INTO EMPLOYEE_LOG(EID,OLDVALUE,NEWVALUE,FIELDNAME,OPERATIONTYPE,LOGDATE)
VALUES(@EID,@ONAME,@NNAME,'FIRSTNAME','UPDATE',GETDATE())
END
 
--4. Create trigger to block employees from updating their JOININGYEAR and print message 
--‘Employees are not allowed to update their joining year’. 
--5. Create trigger for preventing duplicate employee records having same FIRSTNAME, LASTNAME, and CITY. 
 
--Part – B: 
--6. Create INSTEAD OF INSERT trigger to prevent insertion of duplicate EID in EMPLOYEE table. 
--7. Create INSTEAD OF UPDATE trigger to maintain complete employee update history into EMPLOYEE_LOG 
--table. 
--8. Create INSTEAD OF UPDATE trigger to prevent changing employee EID once record is created. 
--9. Create INSTEAD OF INSERT trigger to block insertion of employees with NULL department name. 
--10. Create INSTEAD OF UPDATE trigger to prevent updating GENDER column after employee registration. 
 
--STUDENT_LOG (LOGID, STDID, SNAME, OLDVALUE, NEWVALUE, FIELDNAME, OPERATIONTYPE, LOGDATE)
CREATE TABLE STUDENT_LOG (LOGID INT IDENTITY(1,1) PRIMARY KEY, STDID INT, SNAME VARCHAR(30),
OLDVALUE VARCHAR(30), NEWVALUE VARCHAR(30), FIELDNAME VARCHAR(30), OPERATIONTYPE VARCHAR(30), LOGDATE DATETIME)
--From the table STUDENT perform the following queries:  
--Part – C: 
--11. Create INSTEAD OF INSERT trigger to prevent insertion of students whose SPI is greater than 10 or less 
--than 0. 
CREATE OR ALTER TRIGGER TR_INS_INVA_SPI
ON STUDENT
INSTEAD OF INSERT
AS
BEGIN
DECLARE @SPI DECIMAL(4,2)
SELECT @SPI=SPI FROM inserted
IF @SPI>10 OR @SPI<0
PRINT 'INVALID SPI'
ELSE 
BEGIN
INSERT INTO STUDENT
SELECT * FROM inserted
END
END

--12. Create INSTEAD OF UPDATE trigger to block students from changing their BRANCH after admission.
CREATE OR ALTER TRIGGER TR_PREV_BRNH_UP
ON STUDENT
INSTEAD OF UPDATE
AS
BEGIN
IF UPDATE(BRANCH)
BEGIN
PRINT 'YOU CANNOT CHANGE BRANCH'
END
ELSE
BEGIN
DECLARE @STDID INT,@NAME VARCHAR(30),@CITY VARCHAR(30),@SPI DECIMAL(4,2)
SELECT @STDID=STDID,@NAME=SNAME,@CITY=CITY,@SPI=SPI
FROM inserted
UPDATE STUDENT
SET SNAME=@NAME,CITY=@CITY,SPI=@SPI
WHERE STDID=@STDID
END
END

--13. Create INSTEAD OF DELETE trigger to move deleted student records into STUDENT_LOG table instead of 
--permanent deletion. 
--14. Create INSTEAD OF UPDATE trigger to prevent updating student SPI. 
CREATE OR ALTER TRIGGER TR_PREV_SPI_UP
ON STUDENT
INSTEAD OF UPDATE
AS
BEGIN
IF UPDATE(SPI)
BEGIN
PRINT 'YOU CANNOT CHANGE STUDENT SPI'
END
ELSE
BEGIN
DECLARE @STDID INT,@NAME VARCHAR(30),@CITY VARCHAR(30),@BRANCH VARCHAR(30)
SELECT @STDID=STDID,@NAME=SNAME,@CITY=CITY,@BRANCH=BRANCH
FROM inserted
UPDATE STUDENT
SET SNAME=@NAME,CITY=@CITY,BRANCH=@BRANCH
WHERE STDID=@STDID
END
END

--15. Create INSTEAD OF UPDATE trigger to store student branch transfer history into STUDENT_LOG table. 
CREATE TRIGGER TR_BRNCH_LOG
ON STUDENT
INSTEAD OF UPDATE
AS
BEGIN
DECLARE @STDID INT,@ONAME VARCHAR(30),@NNAME VARCHAR(30),@CITY VARCHAR(30),@SPI DECIMAL(4,2),@BRANCH VARCHAR(30)
IF UPDATE(BRANCH)
BEGIN 
INSERT INTO STUDENT_LOG
VALUES(@STDID,@