--From the table STUDENT perform the following queries:  
--Part – A:  
--1. INSERT Procedures: Create stored procedures to insert records into STUDENT tables 
--(SP_INSERT_STUDENT) 
--STDID SNAME CITY SPI BRANCH 
--115 PUSHTI RAJKOT 9.48 COMPUTER 
--116 NIKUNJ SURAT 8.80 CHEMICAL 
CREATE PROC PR_INSERT_STUDENT
@ID INT,
@NAME VARCHAR(30),
@CITY VARCHAR(30),
@SPI DECIMAL(4,2),
@BRANCH VARCHAR(30)
AS
BEGIN
INSERT INTO STUDENT
VALUES(@ID,@NAME,@CITY,@SPI,@BRANCH)
END

EXEC PR_INSERT_STUDENT 115, 'PUSHTI', 'RAJKOT', 9.48, 'COMPUTER' 
EXEC PR_INSERT_STUDENT 116, 'NIKUNJ', 'SURAT', 8.80, 'CHEMICAL'

--2. INSERT Procedures: Create stored procedures to insert records into DEPOSIT tables  
--(SP_INSERT_DEPOSIT) 
--ACTNO CNAME BNAME AMOUNT ADATE 
--118 HEMENT BEDI 16000 05-05-2025 
--119 RAVI MAVDI 24000 09-07-2024 
CREATE PROC PR_INSERT_DEPOSIT
@ACTNO INT,
@NAME VARCHAR(30),
@BNAME VARCHAR(30),
@AMOUNT DECIMAL(8,2),
@ADATE DATETIME
AS
BEGIN
INSERT INTO DEPOSIT
VALUES(@ACTNO,@NAME,@BNAME,@AMOUNT,@ADATE)
END

EXEC PR_INSERT_DEPOSIT 118, 'HEMENT', 'BEDI', 16000, '2025-05-05'
EXEC PR_INSERT_DEPOSIT 119, 'RAVI', 'MAVDI', 24000, '2024-09-07' 

--3. UPDATE Procedures: Create stored procedure SP_UPDATE_STUDENT to update Branch in STUDENT 
--table. (Update using studentID)
--STDID BRANCH 
--115 ELECTRICAL 
--116 MECHANICAL 
CREATE PROC PR_UPDATE_STUDENT
@ID INT,
@BRANCH VARCHAR(30)
AS
BEGIN
UPDATE STUDENT
SET BRANCH=@BRANCH
WHERE STDID=@ID
END

EXEC PR_UPDATE_STUDENT 115,'ELECTRICAL'
EXEC PR_UPDATE_STUDENT 116,'MECHANICAL'
 
--4. DELETE Procedures: Create stored procedure SP_DELETE_STUDENT to delete records from STUDENT 
--where Student Name is RAVI. 
CREATE OR ALTER PROC PR_DELETE_STUDENT
@NAME VARCHAR(30)
AS
BEGIN
DELETE FROM STUDENT
WHERE SNAME=@NAME
END

EXEC PR_DELETE_STUDENT 'RAVI'


--5. SELECT BY PRIMARY KEY: Create stored procedures to select records by primary key 
--(SP_SELECT_STUDENT_BY_ID) from Student table. (Display All Columns) 
CREATE PROC PR_SELECT_STUDENT_BY_ID
@ID INT
AS
BEGIN
SELECT * 
FROM STUDENT
WHERE STDID=@ID
END

--6. Create a stored procedure that shows details of the first 5 students ordered by SPI (Highest First). 
CREATE OR ALTER PROC PR_TOP_5
AS
BEGIN
SELECT TOP 5 *
FROM STUDENT
ORDER BY SPI DESC
END

EXEC PR_TOP_5

--From the table EMPLOYEE perform the following queries:  
--Part – B:   
--7. Create a stored procedure which displays all employee details. 
CREATE OR ALTER PROC PR_ALL_EMPLOYEE
AS
BEGIN
SELECT *
FROM EMPLOYEE
END

EXEC PR_ALL_EMPLOYEE

--8. Create a stored procedure that takes department name as input and returns all the employee in that 
--department. 
CREATE OR ALTER PROC PR_EMP_BY_DEPT
@DEPT VARCHAR(20)
AS
BEGIN
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT=@DEPT
END

EXEC PR_EMP_BY_DEPT 'IT'

--Part – C:  
--9. Create a stored procedure which displays department-wise maximum, minimum, and average salary of 
--employee. 
CREATE PROC PR_DEPT_SALARY
AS
BEGIN
SELECT DEPARTMENT,MAX(SALARY) MAX_SAL,MIN(SALARY) MIN_SAL,AVG(SALARY) AVG_SAL
FROM EMPLOYEE
GROUP BY DEPARTMENT
END

EXEC PR_DEPT_SALARY 

--10. Create a stored procedure that accepts department name as parameter and returns total salary of their 
--department.
CREATE OR ALTER PROC PR_TOTAL_SAL_BY_DEPT
@DEPT VARCHAR(30),
@TOTAL_SAL DECIMAL(10,2) OUT
AS
BEGIN
SELECT @TOTAL_SAL = SUM(SALARY) 
FROM EMPLOYEE
WHERE DEPARTMENT=@DEPT
END

DECLARE @TOTAL_SALARY DECIMAL(10,2)
EXEC PR_TOTAL_SAL_BY_DEPT 'ADMIN', @TOTAL_SALARY OUT
SELECT @TOTAL_SALARY AS TOTAL_SAL