--CREATE TABLE CUSTOMER_ALL
--(
--ORDERID INT PRIMARY KEY,
--CNAME VARCHAR(50),
--PRODUCT VARCHAR(50),
--CATEGORY VARCHAR(50),
--AMOUNT INT,
--ORDERYEAR INT,
--CITY VARCHAR(50)
--);
--INSERT INTO CUSTOMER_ALL 
--VALUES
--(101, 'RAHUL', 'LAPTOP', 'ELECTRONICS', 65000, 2024, 'RAJKOT'),
--(102, 'PRIYA', 'MOBILE', 'ELECTRONICS', 25000, 2023, 'SURAT'),
--(103, 'AMIT', 'TABLE', 'FURNITURE', 12000, 2022, 'AHMEDABAD'),
--(104, 'NEHA', 'CHAIR', 'FURNITURE', 8000, 2024, 'BARODA'),
--(105, 'VISHAL', 'TV', 'ELECTRONICS', 45000, 2025, 'MORBI'),
--(106, 'RIYA', 'SOFA', 'FURNITURE', 30000, 2023, 'SURAT'),
--(107, 'MEHUL', 'AC', 'ELECTRONICS', 40000, 2022, 'RAJKOT'),
--(108, 'KUNAL', 'BED', 'FURNITURE', 35000, 2025, 'JAMNAGAR');

--Part � A: 
--1. Display top 3 highest amount orders. 
WITH HIGH_ORDERS AS
(
SELECT AMOUNT,ROW_NUMBER() OVER(ORDER BY AMOUNT DESC) RN
FROM CUSTOMER_ALL
)
SELECT AMOUNT
FROM HIGH_ORDERS
WHERE RN<=3

--2. Display second highest order amount. 
WITH HIGH_ORDERS AS
(
SELECT AMOUNT,ROW_NUMBER() OVER(ORDER BY AMOUNT DESC) RN
FROM CUSTOMER_ALL
)
SELECT AMOUNT
FROM HIGH_ORDERS
WHERE RN=2

--3. Display customers whose order amount is greater than category average amount. 
WITH HIGH_ORDERS AS
(
SELECT CNAME,AMOUNT,AVG(AMOUNT) OVER(PARTITION BY CATEGORY) AVG_CAT
FROM CUSTOMER_ALL
)
SELECT CNAME
FROM HIGH_ORDERS
WHERE AMOUNT>AVG_CAT

--4. Display categories having average amount greater than 30000.
WITH CATEGORIES AS
(
SELECT CATEGORY,AVG(AMOUNT) AVG_AMT
FROM CUSTOMER_ALL
GROUP BY CATEGORY
)
SELECT CATEGORY
FROM CATEGORIES
WHERE AVG_AMT>30000

--5. Display highest amount order from each category.
WITH CATEGORIES AS
(
SELECT CATEGORY,AMOUNT,RANK() OVER(PARTITION BY CATEGORY ORDER BY AMOUNT) RK
FROM CUSTOMER_ALL
)
SELECT CATEGORY,AMOUNT
FROM CATEGORIES
WHERE RK=1

--6. Display lowest amount order from each category. 
WITH CATEGORIES AS
(
SELECT CATEGORY,AMOUNT,RANK() OVER(PARTITION BY CATEGORY ORDER BY AMOUNT) RK
FROM CUSTOMER_ALL
)
SELECT CATEGORY,AMOUNT
FROM CATEGORIES
WHERE RK=1

--7. Display categories having more than 3 orders.
WITH CATEGORIES AS
(
SELECT CATEGORY,COUNT(ORDERID) ORDERS
FROM CUSTOMER_ALL
GROUP BY CATEGORY
)
SELECT CATEGORY,ORDERS
FROM CATEGORIES
WHERE ORDERS>3

--8. Display city-wise total order amount. 
WITH CITY_WISE AS
(
SELECT CITY,SUM(AMOUNT) TOTAL_AMT
FROM CUSTOMER_ALL
GROUP BY CITY
)
SELECT CITY,TOTAL_AMT
FROM CITY_WISE

--9. Display category having highest average order amount.
WITH CATEGORIES AS
(
SELECT CATEGORY,AVG(AMOUNT) AVG_AMT
FROM CUSTOMER_ALL
GROUP BY CATEGORY
),
AVG_CAT AS
(
SELECT CATEGORY,RANK() OVER(ORDER BY AVG_AMT DESC) RK_AMT
FROM CATEGORIES
)
SELECT CATEGORY
FROM AVG_CAT
WHERE RK_AMT=1

--10. Display cumulative order amount in ascending order of amount. 
WITH CUM_ORDER AS
(
SELECT SUM(AMOUNT) OVER(ORDER BY AMOUNT ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) C_AMT
FROM CUSTOMER_ALL
)
SELECT C_AMT
FROM CUM_ORDER

 
--Part � B: 
--11. Display category-wise top 2 highest amount orders. 
WITH CATEGORIES AS
(
SELECT ORDERID,CNAME,AMOUNT,CATEGORY,DENSE_RANK() OVER(PARTITION BY CATEGORY ORDER BY AMOUNT DESC) DK
FROM CUSTOMER_ALL
)
SELECT ORDERID,CNAME,AMOUNT,CATEGORY,DK
FROM CATEGORIES
WHERE DK<=2

--12. Display customers whose amount is closest to category average amount. 
WITH CATEGORIES AS
(
SELECT CNAME,AMOUNT,CATEGORY,AVG(AMOUNT) OVER(PARTITION BY CATEGORY) C_AVG
FROM CUSTOMER_ALL
),
CLOSEST AS
(
SELECT CNAME,AMOUNT,CATEGORY,RANK() OVER(PARTITION BY CATEGORY ORDER BY ABS(AMOUNT-C_AVG))  C_AMT
FROM CATEGORIES
)
SELECT CNAME,AMOUNT,CATEGORY,C_AMT
FROM CLOSEST
WHERE C_AMT=1

--13. Display previous, current and next order amount together.
WITH PRE_CURR_NEXT AS
(
SELECT ORDERID,CNAME,LAG(AMOUNT) OVER(ORDER BY AMOUNT) PRE_AMT,AMOUNT,LEAD(AMOUNT) OVER(ORDER BY AMOUNT) NEXT_AMT
FROM CUSTOMER_ALL
)
SELECT *
FROM PRE_CURR_NEXT

--14. Display customers whose amount is greater than previous customer's amount.
WITH PRE_CURR AS
(
SELECT ORDERID,CNAME,LAG(AMOUNT) OVER(ORDER BY AMOUNT) PRE_AMT,AMOUNT
FROM CUSTOMER_ALL
)
SELECT *
FROM PRE_CURR
WHERE AMOUNT>PRE_AMT

--15. Display customers whose rank and dense rank are different.
WITH RANK_DRANK AS
(
SELECT ORDERID,CNAME,AMOUNT,RANK() OVER(ORDER BY AMOUNT) RK,DENSE_RANK() OVER(ORDER BY AMOUNT) DR
FROM CUSTOMER_ALL
)
SELECT *
FROM RANK_DRANK
WHERE RK<>DR
 
--Part � C: 
--16. Display orders whose amount is neither highest nor lowest in their category. 
WITH NOR_HIGH_LOW AS
(
SELECT 

--17. Display category-wise difference between highest and lowest amount. 
--18. Display customers whose amount is greater than all FURNITURE category orders. 
--19. Display categories where all orders are above 10000. 
--20. Display customers whose amount difference from category topper is minimum. 